# Use this to build and run Gazebo 11.

FROM ros:foxy-ros-base-focal

ENV ROS2_DISTRO=foxy

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        sudo \
        ccache \
        wget \
        apt-utils \
    && rm -rf /var/lib/apt/lists/*

# Setup links for ccache
RUN cd /usr/local/bin/ \
    && ln -s ccache gcc && ln -s ccache g++ \
    && ln -s ccache cc && ln -s ccache c++

# Install ROS2 packages.
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-foxy-desktop=0.9.2-1* \
    && rm -rf /var/lib/apt/lists/*

# Install Gazebo packages.
RUN wget http://packages.osrfoundation.org/gazebo.key && apt-key add gazebo.key
RUN echo "deb [arch=amd64] http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -sc` main" > /etc/apt/sources.list.d/gazebo-stable.list
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ros-${ROS2_DISTRO}-gazebo-dev \
        ros-${ROS2_DISTRO}-gazebo-msgs \
        ros-${ROS2_DISTRO}-gazebo-plugins \
        ros-${ROS2_DISTRO}-gazebo-ros \
        ros-${ROS2_DISTRO}-gazebo-ros-pkgs \
        gazebo11 \
        gazebo11-doc \
        libgazebo11-dev \
    && rm -rf /var/lib/apt/lists/*

# Create user with UID and GID matching those on my PC.
# This allows the user to delete build products created in the source tree.
# Also add user build to sudoers list.
RUN groupadd -g 1000 build && \
    useradd -u 1000 -g 1000 -m -s /bin/bash build && \
    mkdir -p /etc/sudoers.d/ && \
    echo "build ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/build && \
    chmod 0440 /etc/sudoers.d/build
ENV HOME /home/build

# Change ownership of build directory to build:build.
RUN chown -R build:build /home/build/

# Change to user build.
USER build
